package com.example.itodo.common.error;

public enum ErrorCode {
    VALIDATION_FAILED,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    RESOURCE_CONFLICT,
    RATE_LIMITED,
    EXTERNAL_AUTH_FAILED,
    INTERNAL_ERROR,
    
    // AI 相关错误
    AI_SERVICE_UNAVAILABLE,
    AI_PARSE_FAILED,
    AI_QUOTA_EXCEEDED,
    INVALID_AI_INPUT,
    AI_TASK_DECOMPOSE_FAILED
}
